
/* Includes added by #pragma extra_include */
#include "vector"
#include "string"
#include "iostream"
/********************************************************************
* core/base/src/G__Base2.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error core/base/src/G__Base2.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Base2();
extern void G__cpp_setup_inheritanceG__Base2();
extern void G__cpp_setup_typetableG__Base2();
extern void G__cpp_setup_memvarG__Base2();
extern void G__cpp_setup_globalG__Base2();
extern void G__cpp_setup_memfuncG__Base2();
extern void G__cpp_setup_funcG__Base2();
extern void G__set_cpp_environmentG__Base2();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TApplication.h"
#include "TApplicationImp.h"
#include "TAtt3D.h"
#include "TAttAxis.h"
#include "TAttBBox.h"
#include "TAttFill.h"
#include "TAttLine.h"
#include "TAttMarker.h"
#include "TAttPad.h"
#include "TAttText.h"
#include "TBenchmark.h"
#include "TBrowser.h"
#include "TBrowserImp.h"
#include "TBuffer3D.h"
#include "TBuffer3DTypes.h"
#include "TBuffer.h"
#include "TCanvasImp.h"
#include "TColor.h"
#include "TContextMenu.h"
#include "TContextMenuImp.h"
#include "TControlBarImp.h"
#include "TDatime.h"
#include "TDirectory.h"
#include "TEnv.h"
#include "TError.h"
#include "TException.h"
#include "TExec.h"
#include "TFolder.h"
#include "TGuiFactory.h"
#include "TInspectorImp.h"
#include "TMacro.h"
#include "TMathBase.h"
#include "TMD5.h"
#include "TMemberInspector.h"
#include "TMessageHandler.h"
#include "TNamed.h"
#include "TObject.h"
#include "TObjString.h"
#include "TPluginManager.h"
#include "TPoint.h"
#include "TPRegexp.h"
#include "TProcessID.h"
#include "TProcessUUID.h"
#include "TQClass.h"
#include "TQCommand.h"
#include "TQConnection.h"
#include "TQObject.h"
#include "TRefCnt.h"
#include "TRef.h"
#include "TRegexp.h"
#include "TRemoteObject.h"
#include "TROOT.h"
#include "TRootIOCtor.h"
#include "TStopwatch.h"
#include "TStorage.h"
#include "TString.h"
#include "TStringLong.h"
#include "TStyle.h"
#include "TSysEvtHandler.h"
#include "TSystemDirectory.h"
#include "TSystemFile.h"
#include "TSystem.h"
#include "TTask.h"
#include "TTime.h"
#include "TTimer.h"
#include "TUUID.h"
#include "TVersionCheck.h"
#include "TVirtualFFT.h"
#include "TVirtualGL.h"
#include "TVirtualPadEditor.h"
#include "TVirtualPad.h"
#include "TVirtualPadPainter.h"
#include "TVirtualPS.h"
#include "TVirtualViewer3D.h"

#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__Base2LN_type_info;
extern G__linked_taginfo G__G__Base2LN_TClass;
extern G__linked_taginfo G__G__Base2LN_TBuffer;
extern G__linked_taginfo G__G__Base2LN_TDirectory;
extern G__linked_taginfo G__G__Base2LN_TMemberInspector;
extern G__linked_taginfo G__G__Base2LN_TObject;
extern G__linked_taginfo G__G__Base2LN_TNamed;
extern G__linked_taginfo G__G__Base2LN_TString;
extern G__linked_taginfo G__G__Base2LN_TVirtualIsAProxy;
extern G__linked_taginfo G__G__Base2LN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base2LN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__Base2LN_string;
extern G__linked_taginfo G__G__Base2LN_stringcLcLiterator;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEstringcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_TStorage;
extern G__linked_taginfo G__G__Base2LN_va_list;
extern G__linked_taginfo G__G__Base2LN_TList;
extern G__linked_taginfo G__G__Base2LN_TBrowser;
extern G__linked_taginfo G__G__Base2LN_TObjArray;
extern G__linked_taginfo G__G__Base2LN_TMethod;
extern G__linked_taginfo G__G__Base2LN_TTimer;
extern G__linked_taginfo G__G__Base2LN_TObjectcLcLEStatusBits;
extern G__linked_taginfo G__G__Base2LN_TObjectcLcLdA;
extern G__linked_taginfo G__G__Base2LN_TProcessID;
extern G__linked_taginfo G__G__Base2LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_TMemberInspectorcLcLTParentBuf;
extern G__linked_taginfo G__G__Base2LN_TRefCnt;
extern G__linked_taginfo G__G__Base2LN_TRefCntcLcLEReferenceFlag;
extern G__linked_taginfo G__G__Base2LN_TRegexp;
extern G__linked_taginfo G__G__Base2LN_TPRegexp;
extern G__linked_taginfo G__G__Base2LN_TSubString;
extern G__linked_taginfo G__G__Base2LN_TStringRef;
extern G__linked_taginfo G__G__Base2LN_TStringLong;
extern G__linked_taginfo G__G__Base2LN_TStringcLcLEStripType;
extern G__linked_taginfo G__G__Base2LN_TStringcLcLECaseCompare;
extern G__linked_taginfo G__G__Base2LN_TQConnection;
extern G__linked_taginfo G__G__Base2LN_TQObject;
extern G__linked_taginfo G__G__Base2LN_TQObjSender;
extern G__linked_taginfo G__G__Base2LN_TSignalHandler;
extern G__linked_taginfo G__G__Base2LN_TApplication;
extern G__linked_taginfo G__G__Base2LN_TStopwatch;
extern G__linked_taginfo G__G__Base2LN_TStopwatchcLcLEState;
extern G__linked_taginfo G__G__Base2LN_TCanvas;
extern G__linked_taginfo G__G__Base2LN_TArrayI;
extern G__linked_taginfo G__G__Base2LN_TColor;
extern G__linked_taginfo G__G__Base2LN_TFunction;
extern G__linked_taginfo G__G__Base2LN_TVirtualPad;
extern G__linked_taginfo G__G__Base2LN_TDatime;
extern G__linked_taginfo G__G__Base2LN_TCollection;
extern G__linked_taginfo G__G__Base2LN_TSeqCollection;
extern G__linked_taginfo G__G__Base2LN_TObjLink;
extern G__linked_taginfo G__G__Base2LN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__Base2LN_TFile;
extern G__linked_taginfo G__G__Base2LN_TInetAddress;
extern G__linked_taginfo G__G__Base2LN_TUUID;
extern G__linked_taginfo G__G__Base2LN_TUUIDcLcLuuid_time_t;
extern G__linked_taginfo G__G__Base2LN_TEnv;
extern G__linked_taginfo G__G__Base2LN_TExec;
extern G__linked_taginfo G__G__Base2LN_TFolder;
extern G__linked_taginfo G__G__Base2LN_TObjString;
extern G__linked_taginfo G__G__Base2LN_TMD5;
extern G__linked_taginfo G__G__Base2LN_TMacro;
extern G__linked_taginfo G__G__Base2LN_TMessageHandler;
extern G__linked_taginfo G__G__Base2LN_THashTable;
extern G__linked_taginfo G__G__Base2LN_TMethodCall;
extern G__linked_taginfo G__G__Base2LN_TPluginManager;
extern G__linked_taginfo G__G__Base2LN_TPluginHandler;
extern G__linked_taginfo G__G__Base2LN_TPoint;
extern G__linked_taginfo G__G__Base2LN_PCREPriv_t;
extern G__linked_taginfo G__G__Base2LN_TPRegexpcLcLdA;
extern G__linked_taginfo G__G__Base2LN_TPMERegexp;
extern G__linked_taginfo G__G__Base2LN_TStringToken;
extern G__linked_taginfo G__G__Base2LN_TExMap;
extern G__linked_taginfo G__G__Base2LN_TBits;
extern G__linked_taginfo G__G__Base2LN_TProcessUUID;
extern G__linked_taginfo G__G__Base2LN_TDictionary;
extern G__linked_taginfo G__G__Base2LN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__Base2LN_TQClass;
extern G__linked_taginfo G__G__Base2LN_TQCommand;
extern G__linked_taginfo G__G__Base2LN_TQUndoManager;
extern G__linked_taginfo G__G__Base2LN_TQSlot;
extern G__linked_taginfo G__G__Base2LN_TRef;
extern G__linked_taginfo G__G__Base2LN_TRefcLcLdA;
extern G__linked_taginfo G__G__Base2LN_TRegexpcLcLEStatVal;
extern G__linked_taginfo G__G__Base2LN_TSystemFile;
extern G__linked_taginfo G__G__Base2LN_TOrdCollection;
extern G__linked_taginfo G__G__Base2LN_TSystemDirectory;
extern G__linked_taginfo G__G__Base2LN_TSystem;
extern G__linked_taginfo G__G__Base2LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__Base2LN_vectorlETStringcOallocatorlETStringgRsPgRcLcLiterator;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Base2LN_TSysEvtHandler;
extern G__linked_taginfo G__G__Base2LN_TFileHandler;
extern G__linked_taginfo G__G__Base2LN_ESignals;
extern G__linked_taginfo G__G__Base2LN_exception;
extern G__linked_taginfo G__G__Base2LN_TStdExceptionHandler;
extern G__linked_taginfo G__G__Base2LN_TStdExceptionHandlercLcLEStatus;
extern G__linked_taginfo G__G__Base2LN_TTime;
extern G__linked_taginfo G__G__Base2LN_TFdSet;
extern G__linked_taginfo G__G__Base2LN_EAccessMode;
extern G__linked_taginfo G__G__Base2LN_ELogLevel;
extern G__linked_taginfo G__G__Base2LN_ELogFacility;
extern G__linked_taginfo G__G__Base2LN_ESysConstants;
extern G__linked_taginfo G__G__Base2LN_EFpeMask;
extern G__linked_taginfo G__G__Base2LN_EFileModeMask;
extern G__linked_taginfo G__G__Base2LN_FileStat_t;
extern G__linked_taginfo G__G__Base2LN_UserGroup_t;
extern G__linked_taginfo G__G__Base2LN_SysInfo_t;
extern G__linked_taginfo G__G__Base2LN_CpuInfo_t;
extern G__linked_taginfo G__G__Base2LN_MemInfo_t;
extern G__linked_taginfo G__G__Base2LN_ProcInfo_t;
extern G__linked_taginfo G__G__Base2LN_RedirectHandle_t;
extern G__linked_taginfo G__G__Base2LN_TProcessEventTimer;
extern G__linked_taginfo G__G__Base2LN_TSystemcLcLEAclicMode;
extern G__linked_taginfo G__G__Base2LN_TSystemcLcLEAclicProperties;
extern G__linked_taginfo G__G__Base2LN_TRemoteObject;
extern G__linked_taginfo G__G__Base2LN_TDataType;
extern G__linked_taginfo G__G__Base2LN_TStyle;
extern G__linked_taginfo G__G__Base2LN_TInterpreter;
extern G__linked_taginfo G__G__Base2LN_TGlobal;
extern G__linked_taginfo G__G__Base2LN_TClassGenerator;
extern G__linked_taginfo G__G__Base2LN_TROOT;
extern G__linked_taginfo G__G__Base2LN_TTask;
extern G__linked_taginfo G__G__Base2LN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__G__Base2LN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator;
extern G__linked_taginfo G__G__Base2LN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<TString,allocator<TString> > G__vectorlETStringcOallocatorlETStringgRsPgR;
typedef vector<TString,allocator<TString> >::iterator G__vectorlETStringcOallocatorlETStringgRsPgRcLcLiterator;
typedef reverse_iterator<vector<TString,allocator<TString> >::iterator> G__reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
typedef vector<string,allocator<string> > G__vectorlEstringcOallocatorlEstringgRsPgR;
typedef vector<string,allocator<string> >::iterator G__vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator;
typedef reverse_iterator<vector<string,allocator<string> >::iterator> G__reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
