/********************************************************************
* proof/proofplayer/src/G__ProofPlayer.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error proof/proofplayer/src/G__ProofPlayer.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__ProofPlayer();
extern void G__cpp_setup_inheritanceG__ProofPlayer();
extern void G__cpp_setup_typetableG__ProofPlayer();
extern void G__cpp_setup_memvarG__ProofPlayer();
extern void G__cpp_setup_globalG__ProofPlayer();
extern void G__cpp_setup_memfuncG__ProofPlayer();
extern void G__cpp_setup_funcG__ProofPlayer();
extern void G__set_cpp_environmentG__ProofPlayer();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TDrawFeedback.h"
#include "TEventIter.h"
#include "TFileMerger.h"
#include "TOutputListSelectorDataMap.h"
#include "TPacketizerAdaptive.h"
#include "TPacketizerFile.h"
#include "TPacketizer.h"
#include "TPacketizerMulti.h"
#include "TPacketizerUnit.h"
#include "TPerfStats.h"
#include "TProofLimitsFinder.h"
#include "TProofOutputFile.h"
#include "TProofPlayer.h"
#include "TProofPlayerLite.h"
#include "TStatus.h"
#include "TVirtualPacketizer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__ProofPlayerLN_TClass;
extern G__linked_taginfo G__G__ProofPlayerLN_TBuffer;
extern G__linked_taginfo G__G__ProofPlayerLN_TDirectory;
extern G__linked_taginfo G__G__ProofPlayerLN_TMemberInspector;
extern G__linked_taginfo G__G__ProofPlayerLN_TObject;
extern G__linked_taginfo G__G__ProofPlayerLN_TNamed;
extern G__linked_taginfo G__G__ProofPlayerLN_TString;
extern G__linked_taginfo G__G__ProofPlayerLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__ProofPlayerLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofPlayerLN_TList;
extern G__linked_taginfo G__G__ProofPlayerLN_TTimer;
extern G__linked_taginfo G__G__ProofPlayerLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__ProofPlayerLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofPlayerLN_TQObject;
extern G__linked_taginfo G__G__ProofPlayerLN_TProof;
extern G__linked_taginfo G__G__ProofPlayerLN_THashList;
extern G__linked_taginfo G__G__ProofPlayerLN_TSeqCollection;
extern G__linked_taginfo G__G__ProofPlayerLN_TDrawFeedback;
extern G__linked_taginfo G__G__ProofPlayerLN_TDSet;
extern G__linked_taginfo G__G__ProofPlayerLN_TDSetElement;
extern G__linked_taginfo G__G__ProofPlayerLN_TFile;
extern G__linked_taginfo G__G__ProofPlayerLN_TSelector;
extern G__linked_taginfo G__G__ProofPlayerLN_TIter;
extern G__linked_taginfo G__G__ProofPlayerLN_TTree;
extern G__linked_taginfo G__G__ProofPlayerLN_TTreeCache;
extern G__linked_taginfo G__G__ProofPlayerLN_TEventList;
extern G__linked_taginfo G__G__ProofPlayerLN_TEntryList;
extern G__linked_taginfo G__G__ProofPlayerLN_TEventIter;
extern G__linked_taginfo G__G__ProofPlayerLN_TEventIterUnit;
extern G__linked_taginfo G__G__ProofPlayerLN_TEventIterObj;
extern G__linked_taginfo G__G__ProofPlayerLN_TEventIterTree;
extern G__linked_taginfo G__G__ProofPlayerLN_TStopwatch;
extern G__linked_taginfo G__G__ProofPlayerLN_TFileMerger;
extern G__linked_taginfo G__G__ProofPlayerLN_TCollection;
extern G__linked_taginfo G__G__ProofPlayerLN_TOutputListSelectorDataMap;
extern G__linked_taginfo G__G__ProofPlayerLN_TSlave;
extern G__linked_taginfo G__G__ProofPlayerLN_TSocket;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofProgressStatus;
extern G__linked_taginfo G__G__ProofPlayerLN_TTime;
extern G__linked_taginfo G__G__ProofPlayerLN_TMap;
extern G__linked_taginfo G__G__ProofPlayerLN_TMessage;
extern G__linked_taginfo G__G__ProofPlayerLN_TNtuple;
extern G__linked_taginfo G__G__ProofPlayerLN_TNtupleD;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofProgressInfo;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualPacketizer;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualPacketizercLcLEUseEstOpt;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualPacketizercLcLEStatusBits;
extern G__linked_taginfo G__G__ProofPlayerLN_TSortedList;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizerAdaptive;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizerAdaptivecLcLTFileNode;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizerAdaptivecLcLTFileStat;
extern G__linked_taginfo G__G__ProofPlayerLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizerFile;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizer;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizercLcLTFileNode;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizercLcLTFileStat;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizerMulti;
extern G__linked_taginfo G__G__ProofPlayerLN_TPacketizerUnit;
extern G__linked_taginfo G__G__ProofPlayerLN_TTimeStamp;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualPerfStats;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualPerfStatscLcLEEventType;
extern G__linked_taginfo G__G__ProofPlayerLN_TH1D;
extern G__linked_taginfo G__G__ProofPlayerLN_TH2D;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualMonitoringWriter;
extern G__linked_taginfo G__G__ProofPlayerLN_TPerfEvent;
extern G__linked_taginfo G__G__ProofPlayerLN_TPerfStats;
extern G__linked_taginfo G__G__ProofPlayerLN_TH1;
extern G__linked_taginfo G__G__ProofPlayerLN_THLimitsFinder;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofLimitsFinder;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofOutputFile;
extern G__linked_taginfo G__G__ProofPlayerLN_TFileCollection;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofPlayer;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofOutputFilecLcLERunType;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofOutputFilecLcLETypeOpt;
extern G__linked_taginfo G__G__ProofPlayerLN_TQueryResult;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualProofPlayer;
extern G__linked_taginfo G__G__ProofPlayerLN_TVirtualProofPlayercLcLEExitStatus;
extern G__linked_taginfo G__G__ProofPlayerLN_TArrayL64;
extern G__linked_taginfo G__G__ProofPlayerLN_TArrayF;
extern G__linked_taginfo G__G__ProofPlayerLN_TArrayI;
extern G__linked_taginfo G__G__ProofPlayerLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__ProofPlayerLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofPlayerLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__ProofPlayerLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofPlayerLite;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofPlayerRemote;
extern G__linked_taginfo G__G__ProofPlayerLN_TMutex;
extern G__linked_taginfo G__G__ProofPlayerLN_TStatus;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofPlayercLcLEStatusBits;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofPlayerLocal;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofPlayerSlave;
extern G__linked_taginfo G__G__ProofPlayerLN_TProofPlayerSuperMaster;
extern G__linked_taginfo G__G__ProofPlayerLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__G__ProofPlayerLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgRcLcLiterator;

/* STUB derived class for protected member access */
