/********************************************************************
* bindings/pyroot/src/G__PyROOT.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error bindings/pyroot/src/G__PyROOT.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__PyROOT();
extern void G__cpp_setup_inheritanceG__PyROOT();
extern void G__cpp_setup_typetableG__PyROOT();
extern void G__cpp_setup_memvarG__PyROOT();
extern void G__cpp_setup_globalG__PyROOT();
extern void G__cpp_setup_memfuncG__PyROOT();
extern void G__cpp_setup_funcG__PyROOT();
extern void G__set_cpp_environmentG__PyROOT();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TPyDispatcher.h"
#include "TPyException.h"
#include "TPyFitFunction.h"
#include "TPyReturn.h"
#include "TPyROOTApplication.h"
#include "TPySelector.h"
#include "TPython.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__PyROOTLN_TClass;
extern G__linked_taginfo G__G__PyROOTLN_TBuffer;
extern G__linked_taginfo G__G__PyROOTLN_TMemberInspector;
extern G__linked_taginfo G__G__PyROOTLN_TObject;
extern G__linked_taginfo G__G__PyROOTLN_TString;
extern G__linked_taginfo G__G__PyROOTLN_ROOT;
extern G__linked_taginfo G__G__PyROOTLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__PyROOTLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__PyROOTLN_TList;
extern G__linked_taginfo G__G__PyROOTLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__PyROOTLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__PyROOTLN__object;
extern G__linked_taginfo G__G__PyROOTLN_TPyDispatcher;
extern G__linked_taginfo G__G__PyROOTLN_exception;
extern G__linked_taginfo G__G__PyROOTLN_PyROOT;
extern G__linked_taginfo G__G__PyROOTLN_PyROOTcLcLTPyException;
extern G__linked_taginfo G__G__PyROOTLN_ROOTcLcLMath;
extern G__linked_taginfo G__G__PyROOTLN_ROOTcLcLMathcLcLIBaseFunctionMultiDim;
extern G__linked_taginfo G__G__PyROOTLN_ROOTcLcLMathcLcLIGradientFunctionMultiDim;
extern G__linked_taginfo G__G__PyROOTLN_ROOTcLcLMathcLcLIGradientMultiDim;
extern G__linked_taginfo G__G__PyROOTLN_TPyMultiGenFunction;
extern G__linked_taginfo G__G__PyROOTLN_TPyMultiGradFunction;
extern G__linked_taginfo G__G__PyROOTLN_TPyReturn;
extern G__linked_taginfo G__G__PyROOTLN_TQObject;
extern G__linked_taginfo G__G__PyROOTLN_TApplication;
extern G__linked_taginfo G__G__PyROOTLN_PyROOTcLcLTPyROOTApplication;
extern G__linked_taginfo G__G__PyROOTLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__PyROOTLN_TSelectorList;
extern G__linked_taginfo G__G__PyROOTLN_TTree;
extern G__linked_taginfo G__G__PyROOTLN_TSelector;
extern G__linked_taginfo G__G__PyROOTLN_TSelectorcLcLEAbort;
extern G__linked_taginfo G__G__PyROOTLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__PyROOTLN_TPySelector;
extern G__linked_taginfo G__G__PyROOTLN_TPython;

/* STUB derived class for protected member access */
