#!/bin/sh 

# give time for Postgres to come up
# see http://openacs.org/forums/message-view?message_id=176100
sleep 4

exec /opt/naviserver/bin/nsd-postgres -z -i -t /web/service-phgt-0/etc/nsd/config-ooo-8080.tcl -u service-phgt-0 -g web

# -b 0.0.0.0:80,0.0.0.0:443,0.0.0.0:53/tcp,0.0.0.0:53/udp

# For AOLserver 4 using privileged ports (usually < 1024), add the flag
# -b youraddress:yourport to the nsd command
