<style><!--
body,td,font,.p,a{font-family:arial,sans-serif}
a,a:link{text-decoration:underline;color:#00c}
a:visited{color:#551a8b}
a:active,.fl a:active{color:#000}
.d,.d a:visited,.d a:link, .d
a:active{font-weight:bold;color:#000;text-decoration:none}
.f,.fl:link,.fl a:link{color:#666}
.g,.g a:visited,.g a:link,.g a:active{color:#000}
.h{color:#a03}
.l{line-height:9pt}
.k,.k a:visited,.k a:link, .k a:hover,.k a:active{font-weight:bold;color:#000;text-decoration:underline}
.p,.p:link,.p a:link{color:#008000}
.x a:visited,.x a:link,.x a:active,.x {text-decoration:none;color:#000}
.q a:visited,.q a:link,.q a:active,.q {text-decoration:none;color:#00c}
.w a:link,.w a:visited,.w {color:#009;text-decoration:none}
.w a:active,.w a:hover{color:#009;text-decoration:underline}
.y{font-weight:bold}
.z {visibility:hidden}
//-->
</style>
