//
// File generated by core/utils/src/rootcint_tmp at Sat Jan 22 22:05:03 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME coredIunixdIsrcdIG__Unix
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G__Unix.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TUnixSystem_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TUnixSystem(void *p = 0);
   static void *newArray_TUnixSystem(Long_t size, void *p);
   static void delete_TUnixSystem(void *p);
   static void deleteArray_TUnixSystem(void *p);
   static void destruct_TUnixSystem(void *p);
   static void streamer_TUnixSystem(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TUnixSystem*)
   {
      ::TUnixSystem *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TUnixSystem >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TUnixSystem", ::TUnixSystem::Class_Version(), "include/TUnixSystem.h", 37,
                  typeid(::TUnixSystem), DefineBehavior(ptr, ptr),
                  &::TUnixSystem::Dictionary, isa_proxy, 0,
                  sizeof(::TUnixSystem) );
      instance.SetNew(&new_TUnixSystem);
      instance.SetNewArray(&newArray_TUnixSystem);
      instance.SetDelete(&delete_TUnixSystem);
      instance.SetDeleteArray(&deleteArray_TUnixSystem);
      instance.SetDestructor(&destruct_TUnixSystem);
      instance.SetStreamerFunc(&streamer_TUnixSystem);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TUnixSystem*)
   {
      return GenerateInitInstanceLocal((::TUnixSystem*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TUnixSystem*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TUnixSystem::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TUnixSystem::Class_Name()
{
   return "TUnixSystem";
}

//______________________________________________________________________________
const char *TUnixSystem::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TUnixSystem*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TUnixSystem::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TUnixSystem*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TUnixSystem::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TUnixSystem*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TUnixSystem::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TUnixSystem*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TUnixSystem::Streamer(TBuffer &R__b)
{
   // Stream an object of class TUnixSystem.

   TSystem::Streamer(R__b);
}

//______________________________________________________________________________
void TUnixSystem::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TUnixSystem.
      TClass *R__cl = ::TUnixSystem::IsA();
      if (R__cl || R__insp.IsA()) { }
      TSystem::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TUnixSystem(void *p) {
      return  p ? new(p) ::TUnixSystem : new ::TUnixSystem;
   }
   static void *newArray_TUnixSystem(Long_t nElements, void *p) {
      return p ? new(p) ::TUnixSystem[nElements] : new ::TUnixSystem[nElements];
   }
   // Wrapper around operator delete
   static void delete_TUnixSystem(void *p) {
      delete ((::TUnixSystem*)p);
   }
   static void deleteArray_TUnixSystem(void *p) {
      delete [] ((::TUnixSystem*)p);
   }
   static void destruct_TUnixSystem(void *p) {
      typedef ::TUnixSystem current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TUnixSystem(TBuffer &buf, void *obj) {
      ((::TUnixSystem*)obj)->::TUnixSystem::Streamer(buf);
   }
} // end of namespace ROOT for class ::TUnixSystem

/********************************************************
* core/unix/src/G__Unix.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG__Unix();

extern "C" void G__set_cpp_environmentG__Unix() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TUnixSystem.h");
  G__cpp_reset_tagtableG__Unix();
}
#include <new>
extern "C" int G__cpp_dllrevG__Unix() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TUnixSystem */
static int G__G__Unix_112_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TUnixSystem* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TUnixSystem[n];
     } else {
       p = new((void*) gvp) TUnixSystem[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TUnixSystem;
     } else {
       p = new((void*) gvp) TUnixSystem;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TUnixSystem*) G__getstructoffset())->CheckChilds();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TUnixSystem*) G__getstructoffset())->CheckSignals((Bool_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TUnixSystem*) G__getstructoffset())->CheckDescriptors());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TUnixSystem*) G__getstructoffset())->DispatchSignals((ESignals) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TUnixSystem*) G__getstructoffset())->DispatchTimers((Bool_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_122(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TUnixSystem*) G__getstructoffset())->ConnectService((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_139(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TUnixSystem::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_140(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TUnixSystem::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_141(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TUnixSystem::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_142(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TUnixSystem::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_146(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TUnixSystem*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_147(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TUnixSystem::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_148(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TUnixSystem::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_149(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TUnixSystem::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Unix_112_0_150(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TUnixSystem::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TUnixSystem G__TTUnixSystem;
static int G__G__Unix_112_0_151(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TUnixSystem*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TUnixSystem*) (soff+(sizeof(TUnixSystem)*i)))->~G__TTUnixSystem();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TUnixSystem*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TUnixSystem*) (soff))->~G__TTUnixSystem();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TUnixSystem */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__Unix {
 public:
  G__Sizep2memfuncG__Unix(): p(&G__Sizep2memfuncG__Unix::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__Unix::*p)();
};

size_t G__get_sizep2memfuncG__Unix()
{
  G__Sizep2memfuncG__Unix a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__Unix() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem))) {
     TUnixSystem *G__Lderived;
     G__Lderived=(TUnixSystem*)0x1000;
     {
       TSystem *G__Lpbase=(TSystem*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem),G__get_linked_tagnum(&G__G__UnixLN_TSystem),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem),G__get_linked_tagnum(&G__G__UnixLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem),G__get_linked_tagnum(&G__G__UnixLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__Unix() {

   /* Setting up typedef entry */
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G__UnixLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__G__UnixLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<unsigned int>",117,G__get_linked_tagnum(&G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__G__UnixLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__UnixLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__UnixLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TUnixSystem */
static void G__setup_memvarTUnixSystem(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem));
   { TUnixSystem *p; p=(TUnixSystem*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__UnixLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__Unix() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTUnixSystem(void) {
   /* TUnixSystem */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem));
   G__memfunc_setup("DynamicPathName",1491,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 2, 1, 2, 0, 
"C - - 10 - lib g - 'Bool_t' 0 'kFALSE' quiet", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLinkedLibraries",1812,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 0, 1, 2, 1, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UnixMakedir",1121,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 3, 2, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixOpendir",1141,(G__InterfaceMethod) NULL, 89, -1, -1, 0, 1, 3, 2, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixGetdirentry",1589,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 1, 3, 2, 1, "Y - - 0 - dir", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixHomedirectory",1794,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 1, 3, 2, 1, "C - - 10 '0' user", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixNow",728,(G__InterfaceMethod) NULL, 110, -1, G__defined_typename("Long64_t"), 0, 0, 3, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixWaitchild",1341,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 3, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixSetitimer",1370,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 3, 2, 0, "l - 'Long_t' 0 - ms", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixSelect",1028,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 4, 3, 2, 0, 
"i - 'Int_t' 0 - nfds U 'TFdSet' - 0 - readready "
"U 'TFdSet' - 0 - writeready l - 'Long_t' 0 - timeout", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixSignal",1026,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 3, 2, 0, 
"i 'ESignals' - 0 - sig Y - 'SigHandler_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixSigname",1128,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 1, 3, 2, 1, "i 'ESignals' - 0 - sig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixSigAlarmInterruptsSyscalls",3138,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 3, 2, 0, "g - 'Bool_t' 0 - set", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixResetSignal",1541,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 3, 2, 0, "i 'ESignals' - 0 - sig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixResetSignals",1656,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 3, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixIgnoreSignal",1638,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 3, 2, 0, 
"i 'ESignals' - 0 - sig g - 'Bool_t' 0 - ignore", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixFilestat",1248,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 2, 3, 2, 0, 
"C - - 10 - path u 'FileStat_t' - 1 - buf", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixFSstat",1017,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 5, 3, 2, 0, 
"C - - 10 - path L - 'Long_t' 0 - id "
"L - 'Long_t' 0 - bsize L - 'Long_t' 0 - blocks "
"L - 'Long_t' 0 - bfree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixTcpConnect",1429,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 3, 3, 2, 0, 
"C - - 10 - hostname i - - 0 - port "
"i - - 0 - tcpwindowsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixUnixConnect",1554,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 3, 2, 0, "i - - 0 - port", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixUnixConnect",1554,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 3, 2, 0, "C - - 10 - path", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixTcpService",1436,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 4, 3, 2, 0, 
"i - - 0 - port g - 'Bool_t' 0 - reuse "
"i - - 0 - backlog i - - 0 - tcpwindowsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixUnixService",1561,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 2, 3, 2, 0, 
"i - - 0 - port i - - 0 - backlog", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixUnixService",1561,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 2, 3, 2, 0, 
"C - - 10 - sockpath i - - 0 - backlog", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixRecv",820,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 4, 3, 2, 0, 
"i - - 0 - sock Y - - 0 - buf "
"i - - 0 - len i - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixSend",814,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 4, 3, 2, 0, 
"i - - 0 - sock Y - - 10 - buf "
"i - - 0 - len i - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindDynLib",963,(G__InterfaceMethod) NULL, 89, -1, -1, 0, 1, 3, 2, 0, "C - - 10 - lib", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixDynLoad",1103,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 3, 2, 0, "C - - 10 - lib", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixDynFindSymbol",1734,(G__InterfaceMethod) NULL, 89, -1, G__defined_typename("Func_t"), 0, 2, 3, 2, 0, 
"C - - 10 - lib C - - 10 - entry", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixDynUnload",1330,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 3, 2, 0, "C - - 10 - lib", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixDynListSymbols",1876,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 3, 2, 0, 
"C - - 10 - lib C - - 10 '\"\"' re", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnixDynListLibs",1525,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 3, 2, 0, "C - - 10 '\"\"' lib", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SearchUtmpEntry",1550,(G__InterfaceMethod) NULL, 89, -1, -1, 0, 2, 3, 2, 0, 
"i - - 0 - nentries C - - 10 - tty", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadUtmpFile",1186,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 3, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TUnixSystem",1149,G__G__Unix_112_0_35, 105, G__get_linked_tagnum(&G__G__UnixLN_TUnixSystem), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetProgname",1125,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetDisplay",1026,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetError",810,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("HostName",799,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DispatchOneEvent",1620,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 'kFALSE' pendingOnly", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Select",608,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"U 'TList' - 0 - active l - 'Long_t' 0 - timeout", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Select",608,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"U 'TFileHandler' - 0 - fh l - 'Long_t' 0 - timeout", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CheckChilds",1077,G__G__Unix_112_0_44, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckSignals",1199,G__G__Unix_112_0_45, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - sync", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckDescriptors",1648,G__G__Unix_112_0_46, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DispatchSignals",1537,G__G__Unix_112_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "i 'ESignals' - 0 - sig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddSignalHandler",1573,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TSignalHandler' - 0 - sh", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("RemoveSignalHandler",1930,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_TSignalHandler), -1, 0, 1, 1, 1, 0, "U 'TSignalHandler' - 0 - sh", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ResetSignal",1121,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"i 'ESignals' - 0 - sig g - 'Bool_t' 0 'kTRUE' reset", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IgnoreSignal",1218,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"i 'ESignals' - 0 - sig g - 'Bool_t' 0 'kTRUE' ignore", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SigAlarmInterruptsSyscalls",2718,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - set", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AddFileHandler",1351,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TFileHandler' - 0 - fh", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("RemoveFileHandler",1708,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_TFileHandler), -1, 0, 1, 1, 1, 0, "U 'TFileHandler' - 0 - fh", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFPEMask",903,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetFPEMask",915,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 'kDefaultMask' mask", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Now",308,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__G__UnixLN_TTime), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AddTimer",778,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTimer' - 0 - ti", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("RemoveTimer",1135,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_TTimer), -1, 0, 1, 1, 1, 0, "U 'TTimer' - 0 - ti", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ResetTimer",1028,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTimer' - 0 - ti", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DispatchTimers",1444,G__G__Unix_112_0_61, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - mode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Sleep",505,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - milliSec", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Exec",389,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - - 10 - shellcmd", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("OpenPipe",800,(G__InterfaceMethod) NULL,69, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - shellcmd C - - 10 - mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ClosePipe",900,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "E - - 0 - pipe", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Exit",410,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - code g - 'Bool_t' 0 'kTRUE' mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Abort",504,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '0' code", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPid",573,(G__InterfaceMethod) NULL,105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StackTrace",997,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MakeDirectory",1331,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("OpenDirectory",1351,(G__InterfaceMethod) NULL,89, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FreeDirectory",1335,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "Y - - 0 - dirp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDirEntry",1105,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 1, "Y - - 0 - dirp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ChangeDirectory",1531,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "C - - 10 - path", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("WorkingDirectory",1686,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("HomeDirectory",1342,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 1, "C - - 10 '0' userName", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("TempDirectory",1355,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("TempFileName",1175,(G__InterfaceMethod) NULL,69, -1, -1, 0, 2, 1, 1, 0, 
"u 'TString' - 1 - base C - - 10 '0' dir", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrependPathName",1500,(G__InterfaceMethod) NULL,67, -1, -1, 0, 2, 1, 1, 1, 
"C - - 10 - dir u 'TString' - 1 - name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ExpandPathName",1390,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "u 'TString' - 1 - patbuf", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ExpandPathName",1390,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - path", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AccessPathName",1376,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - path i 'EAccessMode' - 0 'kFileExists' mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsPathLocal",1076,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "C - - 10 - path", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CopyFile",795,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - from C - - 10 - to "
"g - 'Bool_t' 0 'kFALSE' overwrite", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Rename",600,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - from C - - 10 - to", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Link",398,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - from C - - 10 - to", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Symlink",743,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - from C - - 10 - to", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Unlink",625,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPathInfo",1081,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - path u 'FileStat_t' - 1 - buf", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFsInfo",869,(G__InterfaceMethod) NULL,105, -1, -1, 0, 5, 1, 1, 0, 
"C - - 10 - path L - 'Long_t' 0 - id "
"L - 'Long_t' 0 - bsize L - 'Long_t' 0 - blocks "
"L - 'Long_t' 0 - bfree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Chmod",491,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - file h - 'UInt_t' 0 - mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Umask",513,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - mask", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Utime",516,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - file l - 'Long_t' 0 - modtime "
"l - 'Long_t' 0 - actime", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FindFile",769,(G__InterfaceMethod) NULL,67, -1, -1, 0, 3, 1, 1, 1, 
"C - - 10 - search u 'TString' - 1 - file "
"i 'EAccessMode' - 0 'kFileExists' mode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetUid",578,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - - 10 '0' user", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetGid",564,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - - 10 '0' group", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEffectiveUid",1491,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEffectiveGid",1477,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetUserInfo",1099,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_UserGroup_t), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - uid", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetUserInfo",1099,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_UserGroup_t), -1, 0, 1, 1, 1, 0, "C - - 10 '0' user", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetGroupInfo",1209,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_UserGroup_t), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - gid", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetGroupInfo",1209,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_UserGroup_t), -1, 0, 1, 1, 1, 0, "C - - 10 '0' group", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Getenv",617,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 1, "C - - 10 - name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Setenv",629,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - name C - - 10 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Openlog",724,(G__InterfaceMethod) NULL,121, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - name i - 'Int_t' 0 - options "
"i 'ELogFacility' - 0 - facility", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Syslog",641,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"i 'ELogLevel' - 0 - level C - - 10 - mess", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Closelog",824,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("RedirectOutput",1475,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 3, 1, 1, 0, 
"C - - 10 - name C - - 10 '\"a\"' mode "
"U 'RedirectHandle_t' - 0 '0' h", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AddDynamicPath",1371,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - lib", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDynamicPath",1394,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetDynamicPath",1406,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - lib", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DynFindSymbol",1314,(G__InterfaceMethod) NULL,89, -1, G__defined_typename("Func_t"), 0, 2, 1, 1, 0, 
"C - - 10 - module C - - 10 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Load",384,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - module C - - 10 '\"\"' entry "
"g - 'Bool_t' 0 'kFALSE' system", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Unload",611,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - module", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ListSymbols",1157,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - module C - - 10 '\"\"' re", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ListLibraries",1337,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '\"\"' regexp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetHostByName",1274,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__G__UnixLN_TInetAddress), -1, 0, 1, 1, 1, 0, "C - - 10 - server", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetPeerName",1069,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__G__UnixLN_TInetAddress), -1, 0, 1, 1, 1, 0, "i - - 0 - sock", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetSockName",1073,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__G__UnixLN_TInetAddress), -1, 0, 1, 1, 1, 0, "i - - 0 - sock", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetServiceByName",1581,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - service", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetServiceByPort",1617,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - port", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ConnectService",1435,G__G__Unix_112_0_122, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - server i - - 0 - port "
"i - - 0 - tcpwindowsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OpenConnection",1442,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - server i - - 0 - port "
"i - - 0 '-1' tcpwindowsize", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AnnounceTcpService",1839,(G__InterfaceMethod) NULL,105, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - port g - 'Bool_t' 0 - reuse "
"i - - 0 - backlog i - - 0 '-1' tcpwindowsize", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AnnounceUnixService",1964,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - port i - - 0 - backlog", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AnnounceUnixService",1964,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - sockpath i - - 0 - backlog", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AcceptConnection",1632,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sock", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CloseConnection",1542,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sock g - 'Bool_t' 0 'kFALSE' force", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("RecvRaw",698,(G__InterfaceMethod) NULL,105, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - sock Y - - 0 - buffer "
"i - - 0 - length i - - 0 - flag", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SendRaw",692,(G__InterfaceMethod) NULL,105, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - sock Y - - 10 - buffer "
"i - - 0 - length i - - 0 - flag", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("RecvBuf",685,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sock Y - - 0 - buffer "
"i - - 0 - length", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SendBuf",679,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sock Y - - 10 - buffer "
"i - - 0 - length", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetSockOpt",1007,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sock i - - 0 - option "
"i - - 0 - val", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetSockOpt",995,(G__InterfaceMethod) NULL,105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sock i - - 0 - option "
"I - - 0 - val", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetSysInfo",1003,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 8, "U 'SysInfo_t' - 0 - info", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetCpuInfo",980,(G__InterfaceMethod) NULL,105, -1, -1, 0, 2, 1, 1, 8, 
"U 'CpuInfo_t' - 0 - info i - 'Int_t' 0 '1000' sampleTime", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetMemInfo",971,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 8, "U 'MemInfo_t' - 0 - info", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetProcInfo",1088,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 8, "U 'ProcInfo_t' - 0 - info", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__Unix_112_0_139, 85, G__get_linked_tagnum(&G__G__UnixLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TUnixSystem::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__Unix_112_0_140, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TUnixSystem::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__Unix_112_0_141, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TUnixSystem::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__Unix_112_0_142, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TUnixSystem::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__UnixLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__Unix_112_0_146, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__Unix_112_0_147, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TUnixSystem::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__Unix_112_0_148, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TUnixSystem::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__Unix_112_0_149, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TUnixSystem::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__Unix_112_0_150, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TUnixSystem::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TUnixSystem", 1275, G__G__Unix_112_0_151, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__Unix() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__Unix() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__Unix() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__UnixLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TInetAddress = { "TInetAddress" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TSystem = { "TSystem" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TUnixSystem = { "TUnixSystem" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<unsigned int,allocator<unsigned int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TFileHandler = { "TFileHandler" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_ESignals = { "ESignals" , 101 , -1 };
G__linked_taginfo G__G__UnixLN_TSignalHandler = { "TSignalHandler" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TTime = { "TTime" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_TFdSet = { "TFdSet" , 99 , -1 };
G__linked_taginfo G__G__UnixLN_EAccessMode = { "EAccessMode" , 101 , -1 };
G__linked_taginfo G__G__UnixLN_ELogLevel = { "ELogLevel" , 101 , -1 };
G__linked_taginfo G__G__UnixLN_ELogFacility = { "ELogFacility" , 101 , -1 };
G__linked_taginfo G__G__UnixLN_FileStat_t = { "FileStat_t" , 115 , -1 };
G__linked_taginfo G__G__UnixLN_UserGroup_t = { "UserGroup_t" , 115 , -1 };
G__linked_taginfo G__G__UnixLN_SysInfo_t = { "SysInfo_t" , 115 , -1 };
G__linked_taginfo G__G__UnixLN_CpuInfo_t = { "CpuInfo_t" , 115 , -1 };
G__linked_taginfo G__G__UnixLN_MemInfo_t = { "MemInfo_t" , 115 , -1 };
G__linked_taginfo G__G__UnixLN_ProcInfo_t = { "ProcInfo_t" , 115 , -1 };
G__linked_taginfo G__G__UnixLN_RedirectHandle_t = { "RedirectHandle_t" , 115 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__Unix() {
  G__G__UnixLN_TClass.tagnum = -1 ;
  G__G__UnixLN_TBuffer.tagnum = -1 ;
  G__G__UnixLN_TMemberInspector.tagnum = -1 ;
  G__G__UnixLN_TObject.tagnum = -1 ;
  G__G__UnixLN_TNamed.tagnum = -1 ;
  G__G__UnixLN_TString.tagnum = -1 ;
  G__G__UnixLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G__UnixLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__UnixLN_TList.tagnum = -1 ;
  G__G__UnixLN_TTimer.tagnum = -1 ;
  G__G__UnixLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__G__UnixLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__UnixLN_TInetAddress.tagnum = -1 ;
  G__G__UnixLN_TSystem.tagnum = -1 ;
  G__G__UnixLN_TUnixSystem.tagnum = -1 ;
  G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__G__UnixLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__UnixLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__G__UnixLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__UnixLN_TFileHandler.tagnum = -1 ;
  G__G__UnixLN_ESignals.tagnum = -1 ;
  G__G__UnixLN_TSignalHandler.tagnum = -1 ;
  G__G__UnixLN_TTime.tagnum = -1 ;
  G__G__UnixLN_TFdSet.tagnum = -1 ;
  G__G__UnixLN_EAccessMode.tagnum = -1 ;
  G__G__UnixLN_ELogLevel.tagnum = -1 ;
  G__G__UnixLN_ELogFacility.tagnum = -1 ;
  G__G__UnixLN_FileStat_t.tagnum = -1 ;
  G__G__UnixLN_UserGroup_t.tagnum = -1 ;
  G__G__UnixLN_SysInfo_t.tagnum = -1 ;
  G__G__UnixLN_CpuInfo_t.tagnum = -1 ;
  G__G__UnixLN_MemInfo_t.tagnum = -1 ;
  G__G__UnixLN_ProcInfo_t.tagnum = -1 ;
  G__G__UnixLN_RedirectHandle_t.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__Unix() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TClass);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TObject);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TNamed);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TString);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TList);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TTimer);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TInetAddress);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TSystem);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G__UnixLN_TUnixSystem),sizeof(TUnixSystem),-1,62720,"Interface to Unix OS services",G__setup_memvarTUnixSystem,G__setup_memfuncTUnixSystem);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TFileHandler);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_ESignals);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TSignalHandler);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TTime);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_TFdSet);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_EAccessMode);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_ELogLevel);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_ELogFacility);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_FileStat_t);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_UserGroup_t);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_SysInfo_t);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_CpuInfo_t);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_MemInfo_t);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_ProcInfo_t);
   G__get_linked_tagnum_fwd(&G__G__UnixLN_RedirectHandle_t);
}
extern "C" void G__cpp_setupG__Unix(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__Unix()");
  G__set_cpp_environmentG__Unix();
  G__cpp_setup_tagtableG__Unix();

  G__cpp_setup_inheritanceG__Unix();

  G__cpp_setup_typetableG__Unix();

  G__cpp_setup_memvarG__Unix();

  G__cpp_setup_memfuncG__Unix();
  G__cpp_setup_globalG__Unix();
  G__cpp_setup_funcG__Unix();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__Unix();
  return;
}
class G__cpp_setup_initG__Unix {
  public:
    G__cpp_setup_initG__Unix() { G__add_setup_func("G__Unix",(G__incsetup)(&G__cpp_setupG__Unix)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__Unix() { G__remove_setup_func("G__Unix"); }
};
G__cpp_setup_initG__Unix G__cpp_setup_initializerG__Unix;

