/********************************************************************
* core/unix/src/G__Unix.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error core/unix/src/G__Unix.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Unix();
extern void G__cpp_setup_inheritanceG__Unix();
extern void G__cpp_setup_typetableG__Unix();
extern void G__cpp_setup_memvarG__Unix();
extern void G__cpp_setup_globalG__Unix();
extern void G__cpp_setup_memfuncG__Unix();
extern void G__cpp_setup_funcG__Unix();
extern void G__set_cpp_environmentG__Unix();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TUnixSystem.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__UnixLN_TClass;
extern G__linked_taginfo G__G__UnixLN_TBuffer;
extern G__linked_taginfo G__G__UnixLN_TMemberInspector;
extern G__linked_taginfo G__G__UnixLN_TObject;
extern G__linked_taginfo G__G__UnixLN_TNamed;
extern G__linked_taginfo G__G__UnixLN_TString;
extern G__linked_taginfo G__G__UnixLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__UnixLN_TList;
extern G__linked_taginfo G__G__UnixLN_TTimer;
extern G__linked_taginfo G__G__UnixLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__UnixLN_TInetAddress;
extern G__linked_taginfo G__G__UnixLN_TSystem;
extern G__linked_taginfo G__G__UnixLN_TUnixSystem;
extern G__linked_taginfo G__G__UnixLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__UnixLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__UnixLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__UnixLN_TFileHandler;
extern G__linked_taginfo G__G__UnixLN_ESignals;
extern G__linked_taginfo G__G__UnixLN_TSignalHandler;
extern G__linked_taginfo G__G__UnixLN_TTime;
extern G__linked_taginfo G__G__UnixLN_TFdSet;
extern G__linked_taginfo G__G__UnixLN_EAccessMode;
extern G__linked_taginfo G__G__UnixLN_ELogLevel;
extern G__linked_taginfo G__G__UnixLN_ELogFacility;
extern G__linked_taginfo G__G__UnixLN_FileStat_t;
extern G__linked_taginfo G__G__UnixLN_UserGroup_t;
extern G__linked_taginfo G__G__UnixLN_SysInfo_t;
extern G__linked_taginfo G__G__UnixLN_CpuInfo_t;
extern G__linked_taginfo G__G__UnixLN_MemInfo_t;
extern G__linked_taginfo G__G__UnixLN_ProcInfo_t;
extern G__linked_taginfo G__G__UnixLN_RedirectHandle_t;

/* STUB derived class for protected member access */
