/********************************************************************
* proof/proofx/src/G__Proofx.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error proof/proofx/src/G__Proofx.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Proofx();
extern void G__cpp_setup_inheritanceG__Proofx();
extern void G__cpp_setup_typetableG__Proofx();
extern void G__cpp_setup_memvarG__Proofx();
extern void G__cpp_setup_globalG__Proofx();
extern void G__cpp_setup_memfuncG__Proofx();
extern void G__cpp_setup_funcG__Proofx();
extern void G__set_cpp_environmentG__Proofx();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TXHandler.h"
#include "TXProofMgr.h"
#include "TXProofServ.h"
#include "TXSlave.h"
#include "TXSocket.h"
#include "TXSocketHandler.h"
#include "TXUnixSocket.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__ProofxLN_TClass;
extern G__linked_taginfo G__G__ProofxLN_TBuffer;
extern G__linked_taginfo G__G__ProofxLN_TMemberInspector;
extern G__linked_taginfo G__G__ProofxLN_TObject;
extern G__linked_taginfo G__G__ProofxLN_TNamed;
extern G__linked_taginfo G__G__ProofxLN_TString;
extern G__linked_taginfo G__G__ProofxLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__ProofxLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofxLN_va_list;
extern G__linked_taginfo G__G__ProofxLN_TList;
extern G__linked_taginfo G__G__ProofxLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__ProofxLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofxLN_TXHandler;
extern G__linked_taginfo G__G__ProofxLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__ProofxLN_TSocket;
extern G__linked_taginfo G__G__ProofxLN_TXSocket;
extern G__linked_taginfo G__G__ProofxLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__ProofxLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofxLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__ProofxLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofxLN_TQObject;
extern G__linked_taginfo G__G__ProofxLN_TSysEvtHandler;
extern G__linked_taginfo G__G__ProofxLN_TFileHandler;
extern G__linked_taginfo G__G__ProofxLN_TSignalHandler;
extern G__linked_taginfo G__G__ProofxLN_FileStat_t;
extern G__linked_taginfo G__G__ProofxLN_TObjString;
extern G__linked_taginfo G__G__ProofxLN_TProof;
extern G__linked_taginfo G__G__ProofxLN_TProofDesc;
extern G__linked_taginfo G__G__ProofxLN_TProofLog;
extern G__linked_taginfo G__G__ProofxLN_TProofMgr;
extern G__linked_taginfo G__G__ProofxLN_TStopwatch;
extern G__linked_taginfo G__G__ProofxLN_TXProofMgr;
extern G__linked_taginfo G__G__ProofxLN_TApplication;
extern G__linked_taginfo G__G__ProofxLN_TProofServ;
extern G__linked_taginfo G__G__ProofxLN_TProofLockPath;
extern G__linked_taginfo G__G__ProofxLN_TMessage;
extern G__linked_taginfo G__G__ProofxLN_TMutex;
extern G__linked_taginfo G__G__ProofxLN_TXProofServ;
extern G__linked_taginfo G__G__ProofxLN_TProofServcLcLEQueryAction;
extern G__linked_taginfo G__G__ProofxLN_TXProofServInterruptHandler;
extern G__linked_taginfo G__G__ProofxLN_TXSocketHandler;
extern G__linked_taginfo G__G__ProofxLN_TSlave;
extern G__linked_taginfo G__G__ProofxLN_TXSlave;
extern G__linked_taginfo G__G__ProofxLN_TSemaphore;
extern G__linked_taginfo G__G__ProofxLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__G__ProofxLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ProofxLN_ESockOptions;
extern G__linked_taginfo G__G__ProofxLN_ESendRecvOptions;
extern G__linked_taginfo G__G__ProofxLN_XrdClientMessage;
extern G__linked_taginfo G__G__ProofxLN_XrdClientUnsolMsgSender;
extern G__linked_taginfo G__G__ProofxLN_UnsolRespProcResult;
extern G__linked_taginfo G__G__ProofxLN_XrdClientAbsUnsolMsgHandler;
extern G__linked_taginfo G__G__ProofxLN_XrdProofConn;
extern G__linked_taginfo G__G__ProofxLN_TXUnixSocket;
extern G__linked_taginfo G__G__ProofxLN_TXSockBuf;
extern G__linked_taginfo G__G__ProofxLN_TXSockPipe;
extern G__linked_taginfo G__G__ProofxLN_listlETXSockBufmUcOallocatorlETXSockBufmUgRsPgR;
extern G__linked_taginfo G__G__ProofxLN_TXSocketcLcLEUrgentMsgType;
extern G__linked_taginfo G__G__ProofxLN_listlEintcOallocatorlEintgRsPgR;

/* STUB derived class for protected member access */
