/********************************************************************
* geom/geombuilder/src/G__GeomBuilder.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error geom/geombuilder/src/G__GeomBuilder.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__GeomBuilder();
extern void G__cpp_setup_inheritanceG__GeomBuilder();
extern void G__cpp_setup_typetableG__GeomBuilder();
extern void G__cpp_setup_memvarG__GeomBuilder();
extern void G__cpp_setup_globalG__GeomBuilder();
extern void G__cpp_setup_memfuncG__GeomBuilder();
extern void G__cpp_setup_funcG__GeomBuilder();
extern void G__set_cpp_environmentG__GeomBuilder();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGeoVolumeEditor.h"
#include "TGeoBBoxEditor.h"
#include "TGeoMediumEditor.h"
#include "TGeoNodeEditor.h"
#include "TGeoMatrixEditor.h"
#include "TGeoManagerEditor.h"
#include "TGeoTubeEditor.h"
#include "TGeoConeEditor.h"
#include "TGeoTrd1Editor.h"
#include "TGeoTrd2Editor.h"
#include "TGeoMaterialEditor.h"
#include "TGeoTabManager.h"
#include "TGeoSphereEditor.h"
#include "TGeoPconEditor.h"
#include "TGeoParaEditor.h"
#include "TGeoTorusEditor.h"
#include "TGeoEltuEditor.h"
#include "TGeoHypeEditor.h"
#include "TGeoPgonEditor.h"
#include "TGeoTrapEditor.h"
#include "TGeoGedFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__GeomBuilderLN_TClass;
extern G__linked_taginfo G__G__GeomBuilderLN_TBuffer;
extern G__linked_taginfo G__G__GeomBuilderLN_TMemberInspector;
extern G__linked_taginfo G__G__GeomBuilderLN_TObject;
extern G__linked_taginfo G__G__GeomBuilderLN_TString;
extern G__linked_taginfo G__G__GeomBuilderLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__GeomBuilderLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GeomBuilderLN_TObjArray;
extern G__linked_taginfo G__G__GeomBuilderLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__GeomBuilderLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GeomBuilderLN_TGWindow;
extern G__linked_taginfo G__G__GeomBuilderLN_TGWidget;
extern G__linked_taginfo G__G__GeomBuilderLN_TGObject;
extern G__linked_taginfo G__G__GeomBuilderLN_TQObject;
extern G__linked_taginfo G__G__GeomBuilderLN_TGFrame;
extern G__linked_taginfo G__G__GeomBuilderLN_TGCompositeFrame;
extern G__linked_taginfo G__G__GeomBuilderLN_TGLayoutHints;
extern G__linked_taginfo G__G__GeomBuilderLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__GeomBuilderLN_TGTextButton;
extern G__linked_taginfo G__G__GeomBuilderLN_TGMainFrame;
extern G__linked_taginfo G__G__GeomBuilderLN_TGTransientFrame;
extern G__linked_taginfo G__G__GeomBuilderLN_TVirtualPad;
extern G__linked_taginfo G__G__GeomBuilderLN_TCanvas;
extern G__linked_taginfo G__G__GeomBuilderLN_TGLabel;
extern G__linked_taginfo G__G__GeomBuilderLN_TGTab;
extern G__linked_taginfo G__G__GeomBuilderLN_TGedEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGedFrame;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTabManager;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoGedFrame;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoManager;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoVolume;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoShape;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMedium;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMaterial;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMatrix;
extern G__linked_taginfo G__G__GeomBuilderLN_TGTextEntry;
extern G__linked_taginfo G__G__GeomBuilderLN_TGNumberEntry;
extern G__linked_taginfo G__G__GeomBuilderLN_TGComboBox;
extern G__linked_taginfo G__G__GeomBuilderLN_TGPictureButton;
extern G__linked_taginfo G__G__GeomBuilderLN_TGCheckButton;
extern G__linked_taginfo G__G__GeomBuilderLN_TGRadioButton;
extern G__linked_taginfo G__G__GeomBuilderLN_TGShutter;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoVolumeEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoBBox;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoBBoxEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMediumEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoNode;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoNodeEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTranslation;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoRotation;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoCombiTrans;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTranslationEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoRotationEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoCombiTransEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoManagerEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTube;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTubeEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGDoubleVSlider;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTubeSegEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoCtubEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoCone;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoConeEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoConeSegEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTrd1;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTrd1Editor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTrd2;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTrd2Editor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGCanvas;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMaterialEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMixture;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMixtureEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TMap;
extern G__linked_taginfo G__G__GeomBuilderLN_TGListTree;
extern G__linked_taginfo G__G__GeomBuilderLN_TGListTreeItem;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTreeDialog;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTransientPanel;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoVolumeDialog;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoShapeDialog;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMediumDialog;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMaterialDialog;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoMatrixDialog;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoSphere;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoSphereEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoPcon;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoPconSection;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoPconEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoPara;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoParaEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTorus;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTorusEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoEltu;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoEltuEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoHype;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoHypeEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoPgonEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTrap;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoTrapEditor;
extern G__linked_taginfo G__G__GeomBuilderLN_TGeoGtraEditor;

/* STUB derived class for protected member access */
