all:
	#g++ -I/opt/mongodb/include/mongo -L/opt/mongodb/lib64/ -lmongoclient -lboost_thread-mt -lboost_filesystem -lboost_program_options -o tutorial-cxx tutorial.cpp /opt/mongodb/lib64/libmongoclient.a
	g++ -I/opt/mongodb/include/mongo -L/opt/mongodb/lib/ -lmongoclient -lboost_thread-mt -lboost_filesystem -lboost_program_options -o tutorial-cxx tutorial.cpp

clean:
	rm -f tutorial-cxx

