/********************************************************************
* cint/cint/lib/dll_stl/G__cpp_vector.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cint/cint/lib/dll_stl/G__cpp_vector.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable();
extern void G__cpp_setup_inheritance();
extern void G__cpp_setup_typetable();
extern void G__cpp_setup_memvar();
extern void G__cpp_setup_global();
extern void G__cpp_setup_memfunc();
extern void G__cpp_setup_func();
extern void G__set_cpp_environment();
}


#include "cint/cint/lib/dll_stl/vec.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LN_allocatorlEchargR;
extern G__linked_taginfo G__LN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__LN_vectorlEcharcOallocatorlEchargRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEcharcOallocatorlEchargRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEshortgR;
extern G__linked_taginfo G__LN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__LN_vectorlEshortcOallocatorlEshortgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEshortcOallocatorlEshortgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlElonggR;
extern G__linked_taginfo G__LN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__LN_vectorlElongcOallocatorlElonggRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlElongcOallocatorlElonggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlElongsPlonggR;
extern G__linked_taginfo G__LN_vectorlElongsPlongcOallocatorlElongsPlonggRsPgR;
extern G__linked_taginfo G__LN_vectorlElongsPlongcOallocatorlElongsPlonggRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlElongsPlongcOallocatorlElongsPlonggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEunsignedsPchargR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEunsignedsPshortgR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEunsignedsPintgR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEunsignedsPlonggR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEunsignedsPlongsPlonggR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgR;
extern G__linked_taginfo G__LN_vectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEfloatgR;
extern G__linked_taginfo G__LN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__LN_vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEdoublegR;
extern G__linked_taginfo G__LN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEvoidmUgR;
extern G__linked_taginfo G__LN_vectorlEvoidmUcOallocatorlEvoidmUgRsPgR;
extern G__linked_taginfo G__LN_vectorlEvoidmUcOallocatorlEvoidmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEvoidmUcOallocatorlEvoidmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEcharmUgR;
extern G__linked_taginfo G__LN_vectorlEcharmUcOallocatorlEcharmUgRsPgR;
extern G__linked_taginfo G__LN_vectorlEcharmUcOallocatorlEcharmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEcharmUcOallocatorlEcharmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef allocator<char> G__allocatorlEchargR;
typedef vector<char,allocator<char> > G__vectorlEcharcOallocatorlEchargRsPgR;
typedef vector<char,allocator<char> >::iterator G__vectorlEcharcOallocatorlEchargRsPgRcLcLiterator;
typedef reverse_iterator<vector<char,allocator<char> >::iterator> G__reverse_iteratorlEvectorlEcharcOallocatorlEchargRsPgRcLcLiteratorgR;
typedef allocator<short> G__allocatorlEshortgR;
typedef vector<short,allocator<short> > G__vectorlEshortcOallocatorlEshortgRsPgR;
typedef vector<short,allocator<short> >::iterator G__vectorlEshortcOallocatorlEshortgRsPgRcLcLiterator;
typedef reverse_iterator<vector<short,allocator<short> >::iterator> G__reverse_iteratorlEvectorlEshortcOallocatorlEshortgRsPgRcLcLiteratorgR;
typedef allocator<long> G__allocatorlElonggR;
typedef vector<long,allocator<long> > G__vectorlElongcOallocatorlElonggRsPgR;
typedef vector<long,allocator<long> >::iterator G__vectorlElongcOallocatorlElonggRsPgRcLcLiterator;
typedef reverse_iterator<vector<long,allocator<long> >::iterator> G__reverse_iteratorlEvectorlElongcOallocatorlElonggRsPgRcLcLiteratorgR;
typedef allocator<long long> G__allocatorlElongsPlonggR;
typedef vector<long long,allocator<long long> > G__vectorlElongsPlongcOallocatorlElongsPlonggRsPgR;
typedef vector<long long,allocator<long long> >::iterator G__vectorlElongsPlongcOallocatorlElongsPlonggRsPgRcLcLiterator;
typedef reverse_iterator<vector<long long,allocator<long long> >::iterator> G__reverse_iteratorlEvectorlElongsPlongcOallocatorlElongsPlonggRsPgRcLcLiteratorgR;
typedef allocator<unsigned char> G__allocatorlEunsignedsPchargR;
typedef vector<unsigned char,allocator<unsigned char> > G__vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR;
typedef vector<unsigned char,allocator<unsigned char> >::iterator G__vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgRcLcLiterator;
typedef reverse_iterator<vector<unsigned char,allocator<unsigned char> >::iterator> G__reverse_iteratorlEvectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgRcLcLiteratorgR;
typedef allocator<unsigned short> G__allocatorlEunsignedsPshortgR;
typedef vector<unsigned short,allocator<unsigned short> > G__vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
typedef vector<unsigned short,allocator<unsigned short> >::iterator G__vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcLcLiterator;
typedef reverse_iterator<vector<unsigned short,allocator<unsigned short> >::iterator> G__reverse_iteratorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcLcLiteratorgR;
typedef allocator<unsigned int> G__allocatorlEunsignedsPintgR;
typedef vector<unsigned int,allocator<unsigned int> > G__vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
typedef vector<unsigned int,allocator<unsigned int> >::iterator G__vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiterator;
typedef reverse_iterator<vector<unsigned int,allocator<unsigned int> >::iterator> G__reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
typedef allocator<unsigned long> G__allocatorlEunsignedsPlonggR;
typedef vector<unsigned long,allocator<unsigned long> > G__vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
typedef vector<unsigned long,allocator<unsigned long> >::iterator G__vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcLcLiterator;
typedef reverse_iterator<vector<unsigned long,allocator<unsigned long> >::iterator> G__reverse_iteratorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcLcLiteratorgR;
typedef allocator<unsigned long long> G__allocatorlEunsignedsPlongsPlonggR;
typedef vector<unsigned long long,allocator<unsigned long long> > G__vectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgR;
typedef vector<unsigned long long,allocator<unsigned long long> >::iterator G__vectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgRcLcLiterator;
typedef reverse_iterator<vector<unsigned long long,allocator<unsigned long long> >::iterator> G__reverse_iteratorlEvectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgRcLcLiteratorgR;
typedef allocator<float> G__allocatorlEfloatgR;
typedef vector<float,allocator<float> > G__vectorlEfloatcOallocatorlEfloatgRsPgR;
typedef vector<float,allocator<float> >::iterator G__vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
typedef reverse_iterator<vector<float,allocator<float> >::iterator> G__reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
typedef allocator<double> G__allocatorlEdoublegR;
typedef vector<double,allocator<double> > G__vectorlEdoublecOallocatorlEdoublegRsPgR;
typedef vector<double,allocator<double> >::iterator G__vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator;
typedef reverse_iterator<vector<double,allocator<double> >::iterator> G__reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
typedef allocator<void*> G__allocatorlEvoidmUgR;
typedef vector<void*,allocator<void*> > G__vectorlEvoidmUcOallocatorlEvoidmUgRsPgR;
typedef vector<void*,allocator<void*> >::iterator G__vectorlEvoidmUcOallocatorlEvoidmUgRsPgRcLcLiterator;
typedef reverse_iterator<vector<void*,allocator<void*> >::iterator> G__reverse_iteratorlEvectorlEvoidmUcOallocatorlEvoidmUgRsPgRcLcLiteratorgR;
typedef allocator<char*> G__allocatorlEcharmUgR;
typedef vector<char*,allocator<char*> > G__vectorlEcharmUcOallocatorlEcharmUgRsPgR;
typedef vector<char*,allocator<char*> >::iterator G__vectorlEcharmUcOallocatorlEcharmUgRsPgRcLcLiterator;
typedef reverse_iterator<vector<char*,allocator<char*> >::iterator> G__reverse_iteratorlEvectorlEcharmUcOallocatorlEcharmUgRsPgRcLcLiteratorgR;
