/********************************************************************
* cint/cint/lib/dll_stl/G__cpp_stdexcept.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cint/cint/lib/dll_stl/G__cpp_stdexcept.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable();
extern void G__cpp_setup_inheritance();
extern void G__cpp_setup_typetable();
extern void G__cpp_setup_memvar();
extern void G__cpp_setup_global();
extern void G__cpp_setup_memfunc();
extern void G__cpp_setup_func();
extern void G__set_cpp_environment();
}


#include "cint/cint/lib/dll_stl/se.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LN_exception;
extern G__linked_taginfo G__LN_string;
extern G__linked_taginfo G__LN_logic_error;
extern G__linked_taginfo G__LN_domain_error;
extern G__linked_taginfo G__LN_invalid_argument;
extern G__linked_taginfo G__LN_length_error;
extern G__linked_taginfo G__LN_out_of_range;
extern G__linked_taginfo G__LN_runtime_error;
extern G__linked_taginfo G__LN_range_error;
extern G__linked_taginfo G__LN_overflow_error;
extern G__linked_taginfo G__LN_underflow_error;

/* STUB derived class for protected member access */
