/********************************************************************
* cint/cint/lib/dll_stl/G__cpp_complex.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cint/cint/lib/dll_stl/G__cpp_complex.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable();
extern void G__cpp_setup_inheritance();
extern void G__cpp_setup_typetable();
extern void G__cpp_setup_memvar();
extern void G__cpp_setup_global();
extern void G__cpp_setup_memfunc();
extern void G__cpp_setup_func();
extern void G__set_cpp_environment();
}


#include "cint/cint/lib/dll_stl/cmplx.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__LN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__LN_complexlEintgR;
extern G__linked_taginfo G__LN_complexlElonggR;
extern G__linked_taginfo G__LN_complexlEfloatgR;
extern G__linked_taginfo G__LN_complexlEdoublegR;
extern G__linked_taginfo G__LN_complexlElongsPlonggR;
extern G__linked_taginfo G__LN_complexlElongsPdoublegR;

/* STUB derived class for protected member access */
typedef complex<int> G__complexlEintgR;
typedef complex<long> G__complexlElonggR;
typedef complex<float> G__complexlEfloatgR;
typedef complex<double> G__complexlEdoublegR;
typedef complex<long long> G__complexlElongsPlonggR;
typedef complex<long double> G__complexlElongsPdoublegR;
