/********************************************************************
* cint/cint/lib/dll_stl/G__cpp_multiset.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cint/cint/lib/dll_stl/G__cpp_multiset.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable();
extern void G__cpp_setup_inheritance();
extern void G__cpp_setup_typetable();
extern void G__cpp_setup_memvar();
extern void G__cpp_setup_global();
extern void G__cpp_setup_memfunc();
extern void G__cpp_setup_func();
extern void G__set_cpp_environment();
}


#include "cint/cint/lib/dll_stl/multst.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LN_string;
extern G__linked_taginfo G__LN_lesslEintgR;
extern G__linked_taginfo G__LN_binary_functionlEintcOintcOboolgR;
extern G__linked_taginfo G__LN_allocatorlEintgR;
extern G__linked_taginfo G__LN_multisetlEintcOlesslEintgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LN_multisetlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_multisetlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__LN_lesslElonggR;
extern G__linked_taginfo G__LN_binary_functionlElongcOlongcOboolgR;
extern G__linked_taginfo G__LN_allocatorlElonggR;
extern G__linked_taginfo G__LN_multisetlElongcOlesslElonggRcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__LN_multisetlElongcOlesslElonggRcOallocatorlElonggRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_multisetlElongcOlesslElonggRcOallocatorlElonggRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__LN_lesslEfloatgR;
extern G__linked_taginfo G__LN_binary_functionlEfloatcOfloatcOboolgR;
extern G__linked_taginfo G__LN_allocatorlEfloatgR;
extern G__linked_taginfo G__LN_multisetlEfloatcOlesslEfloatgRcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__LN_multisetlEfloatcOlesslEfloatgRcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_multisetlEfloatcOlesslEfloatgRcOallocatorlEfloatgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__LN_lesslEdoublegR;
extern G__linked_taginfo G__LN_binary_functionlEdoublecOdoublecOboolgR;
extern G__linked_taginfo G__LN_allocatorlEdoublegR;
extern G__linked_taginfo G__LN_multisetlEdoublecOlesslEdoublegRcOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LN_multisetlEdoublecOlesslEdoublegRcOallocatorlEdoublegRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_multisetlEdoublecOlesslEdoublegRcOallocatorlEdoublegRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__LN_lesslEvoidmUgR;
extern G__linked_taginfo G__LN_binary_functionlEvoidmUcOvoidmUcOboolgR;
extern G__linked_taginfo G__LN_allocatorlEvoidmUgR;
extern G__linked_taginfo G__LN_multisetlEvoidmUcOlesslEvoidmUgRcOallocatorlEvoidmUgRsPgR;
extern G__linked_taginfo G__LN_multisetlEvoidmUcOlesslEvoidmUgRcOallocatorlEvoidmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_multisetlEvoidmUcOlesslEvoidmUgRcOallocatorlEvoidmUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__LN_lesslEcharmUgR;
extern G__linked_taginfo G__LN_binary_functionlEcharmUcOcharmUcOboolgR;
extern G__linked_taginfo G__LN_allocatorlEcharmUgR;
extern G__linked_taginfo G__LN_multisetlEcharmUcOlesslEcharmUgRcOallocatorlEcharmUgRsPgR;
extern G__linked_taginfo G__LN_multisetlEcharmUcOlesslEcharmUgRcOallocatorlEcharmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_multisetlEcharmUcOlesslEcharmUgRcOallocatorlEcharmUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__LN_lesslEstringgR;
extern G__linked_taginfo G__LN_binary_functionlEstringcOstringcOboolgR;
extern G__linked_taginfo G__LN_allocatorlEstringgR;
extern G__linked_taginfo G__LN_multisetlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__LN_multisetlEstringcOlesslEstringgRcOallocatorlEstringgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_multisetlEstringcOlesslEstringgRcOallocatorlEstringgRsPgRcLcLreverse_iterator;

/* STUB derived class for protected member access */
typedef less<int> G__lesslEintgR;
typedef binary_function<int,int,bool> G__binary_functionlEintcOintcOboolgR;
typedef allocator<int> G__allocatorlEintgR;
typedef multiset<int,less<int>,allocator<int> > G__multisetlEintcOlesslEintgRcOallocatorlEintgRsPgR;
typedef multiset<int,less<int>,allocator<int> >::iterator G__multisetlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLiterator;
typedef multiset<int,less<int>,allocator<int> >::reverse_iterator G__multisetlEintcOlesslEintgRcOallocatorlEintgRsPgRcLcLreverse_iterator;
typedef less<long> G__lesslElonggR;
typedef binary_function<long,long,bool> G__binary_functionlElongcOlongcOboolgR;
typedef allocator<long> G__allocatorlElonggR;
typedef multiset<long,less<long>,allocator<long> > G__multisetlElongcOlesslElonggRcOallocatorlElonggRsPgR;
typedef multiset<long,less<long>,allocator<long> >::iterator G__multisetlElongcOlesslElonggRcOallocatorlElonggRsPgRcLcLiterator;
typedef multiset<long,less<long>,allocator<long> >::reverse_iterator G__multisetlElongcOlesslElonggRcOallocatorlElonggRsPgRcLcLreverse_iterator;
typedef less<float> G__lesslEfloatgR;
typedef binary_function<float,float,bool> G__binary_functionlEfloatcOfloatcOboolgR;
typedef allocator<float> G__allocatorlEfloatgR;
typedef multiset<float,less<float>,allocator<float> > G__multisetlEfloatcOlesslEfloatgRcOallocatorlEfloatgRsPgR;
typedef multiset<float,less<float>,allocator<float> >::iterator G__multisetlEfloatcOlesslEfloatgRcOallocatorlEfloatgRsPgRcLcLiterator;
typedef multiset<float,less<float>,allocator<float> >::reverse_iterator G__multisetlEfloatcOlesslEfloatgRcOallocatorlEfloatgRsPgRcLcLreverse_iterator;
typedef less<double> G__lesslEdoublegR;
typedef binary_function<double,double,bool> G__binary_functionlEdoublecOdoublecOboolgR;
typedef allocator<double> G__allocatorlEdoublegR;
typedef multiset<double,less<double>,allocator<double> > G__multisetlEdoublecOlesslEdoublegRcOallocatorlEdoublegRsPgR;
typedef multiset<double,less<double>,allocator<double> >::iterator G__multisetlEdoublecOlesslEdoublegRcOallocatorlEdoublegRsPgRcLcLiterator;
typedef multiset<double,less<double>,allocator<double> >::reverse_iterator G__multisetlEdoublecOlesslEdoublegRcOallocatorlEdoublegRsPgRcLcLreverse_iterator;
typedef less<void*> G__lesslEvoidmUgR;
typedef binary_function<void*,void*,bool> G__binary_functionlEvoidmUcOvoidmUcOboolgR;
typedef allocator<void*> G__allocatorlEvoidmUgR;
typedef multiset<void*,less<void*>,allocator<void*> > G__multisetlEvoidmUcOlesslEvoidmUgRcOallocatorlEvoidmUgRsPgR;
typedef multiset<void*,less<void*>,allocator<void*> >::iterator G__multisetlEvoidmUcOlesslEvoidmUgRcOallocatorlEvoidmUgRsPgRcLcLiterator;
typedef multiset<void*,less<void*>,allocator<void*> >::reverse_iterator G__multisetlEvoidmUcOlesslEvoidmUgRcOallocatorlEvoidmUgRsPgRcLcLreverse_iterator;
typedef less<char*> G__lesslEcharmUgR;
typedef binary_function<char*,char*,bool> G__binary_functionlEcharmUcOcharmUcOboolgR;
typedef allocator<char*> G__allocatorlEcharmUgR;
typedef multiset<char*,less<char*>,allocator<char*> > G__multisetlEcharmUcOlesslEcharmUgRcOallocatorlEcharmUgRsPgR;
typedef multiset<char*,less<char*>,allocator<char*> >::iterator G__multisetlEcharmUcOlesslEcharmUgRcOallocatorlEcharmUgRsPgRcLcLiterator;
typedef multiset<char*,less<char*>,allocator<char*> >::reverse_iterator G__multisetlEcharmUcOlesslEcharmUgRcOallocatorlEcharmUgRsPgRcLcLreverse_iterator;
typedef less<string> G__lesslEstringgR;
typedef binary_function<string,string,bool> G__binary_functionlEstringcOstringcOboolgR;
typedef allocator<string> G__allocatorlEstringgR;
typedef multiset<string,less<string>,allocator<string> > G__multisetlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
typedef multiset<string,less<string>,allocator<string> >::iterator G__multisetlEstringcOlesslEstringgRcOallocatorlEstringgRsPgRcLcLiterator;
typedef multiset<string,less<string>,allocator<string> >::reverse_iterator G__multisetlEstringcOlesslEstringgRcOallocatorlEstringgRsPgRcLcLreverse_iterator;
