/********************************************************************
* cint/cint/lib/dll_stl/rootcint_vector.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cint/cint/lib/dll_stl/rootcint_vector.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootcint_vector();
extern void G__cpp_setup_inheritancerootcint_vector();
extern void G__cpp_setup_typetablerootcint_vector();
extern void G__cpp_setup_memvarrootcint_vector();
extern void G__cpp_setup_globalrootcint_vector();
extern void G__cpp_setup_memfuncrootcint_vector();
extern void G__cpp_setup_funcrootcint_vector();
extern void G__set_cpp_environmentrootcint_vector();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "vector"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootcint_vectorLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootcint_vectorLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootcint_vectorLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootcint_vectorLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
