/********************************************************************
* core/metautils/src/G__MetaUtils.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error core/metautils/src/G__MetaUtils.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__MetaUtils();
extern void G__cpp_setup_inheritanceG__MetaUtils();
extern void G__cpp_setup_typetableG__MetaUtils();
extern void G__cpp_setup_memvarG__MetaUtils();
extern void G__cpp_setup_globalG__MetaUtils();
extern void G__cpp_setup_memfuncG__MetaUtils();
extern void G__cpp_setup_funcG__MetaUtils();
extern void G__set_cpp_environmentG__MetaUtils();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RConversionRuleParser.h"
#include "TClassEdit.h"
#include "TSchemaRuleProcessor.h"
#include "TSchemaType.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__MetaUtilsLN_string;
extern G__linked_taginfo G__G__MetaUtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__MetaUtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MetaUtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__MetaUtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MetaUtilsLN_TClassEdit;
extern G__linked_taginfo G__G__MetaUtilsLN_TClassEditcLcLEModType;
extern G__linked_taginfo G__G__MetaUtilsLN_TClassEditcLcLESTLType;
extern G__linked_taginfo G__G__MetaUtilsLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__G__MetaUtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
