#!/bin/sh 

# give time for Postgres to come up
# see http://openacs.org/forums/message-view?message_id=176100
sleep 4

exec /opt/aolserver/bin/nsd-postgres -zit /web/service/phigita.net/etc/nsd/config-8002.tcl -u webroot -g web

# -b 0.0.0.0:80,0.0.0.0:443,0.0.0.0:53/tcp,0.0.0.0:53/udp

# For AOLserver 4 using privileged ports (usually < 1024), add the flag
# -b youraddress:yourport to the nsd command
