/********************************************************************
* graf2d/gviz/src/G__Gviz.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error graf2d/gviz/src/G__Gviz.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Gviz();
extern void G__cpp_setup_inheritanceG__Gviz();
extern void G__cpp_setup_typetableG__Gviz();
extern void G__cpp_setup_memvarG__Gviz();
extern void G__cpp_setup_globalG__Gviz();
extern void G__cpp_setup_memfuncG__Gviz();
extern void G__cpp_setup_funcG__Gviz();
extern void G__set_cpp_environmentG__Gviz();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGraphEdge.h"
#include "TGraphNode.h"
#include "TGraphStruct.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__GvizLN_TClass;
extern G__linked_taginfo G__G__GvizLN_TBuffer;
extern G__linked_taginfo G__G__GvizLN_TMemberInspector;
extern G__linked_taginfo G__G__GvizLN_TObject;
extern G__linked_taginfo G__G__GvizLN_TNamed;
extern G__linked_taginfo G__G__GvizLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__GvizLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__GvizLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GvizLN_TList;
extern G__linked_taginfo G__G__GvizLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__GvizLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GvizLN_TAttLine;
extern G__linked_taginfo G__G__GvizLN_Agraph_t;
extern G__linked_taginfo G__G__GvizLN_Agedge_t;
extern G__linked_taginfo G__G__GvizLN_TGraphNode;
extern G__linked_taginfo G__G__GvizLN_TGraphEdge;
extern G__linked_taginfo G__G__GvizLN_TAttText;
extern G__linked_taginfo G__G__GvizLN_TAttFill;
extern G__linked_taginfo G__G__GvizLN_Agnode_t;
extern G__linked_taginfo G__G__GvizLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__GvizLN_GVC_s;
extern G__linked_taginfo G__G__GvizLN_TGraphStruct;

/* STUB derived class for protected member access */
