/********************************************************************
* cint/cint/lib/G__c_posix.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cint/cint/lib/G__c_posix.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern void G__c_setup_tagtable();
extern void G__c_setup_typetable();
extern void G__c_setup_memvar();
extern void G__c_setup_global();
extern void G__c_setup_func();
extern void G__set_c_environment();


#include "cint/cint/lib/posix/exten.h"
#include "cint/cint/lib/posix/posix.h"
extern G__linked_taginfo G__LN___dirstream;
extern G__linked_taginfo G__LN_dirent;
extern G__linked_taginfo G__LN_stat;
extern G__linked_taginfo G__LN_utsname;

/* STUB derived class for protected member access */
