/********************************************************************
* gui/guihtml/src/G__GuiHtml.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error gui/guihtml/src/G__GuiHtml.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__GuiHtml();
extern void G__cpp_setup_inheritanceG__GuiHtml();
extern void G__cpp_setup_typetableG__GuiHtml();
extern void G__cpp_setup_memvarG__GuiHtml();
extern void G__cpp_setup_globalG__GuiHtml();
extern void G__cpp_setup_memfuncG__GuiHtml();
extern void G__cpp_setup_funcG__GuiHtml();
extern void G__set_cpp_environmentG__GuiHtml();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGHtmlBrowser.h"
#include "TGHtml.h"
#include "TGHtmlTokens.h"
#include "TGHtmlUri.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__GuiHtmlLN_TClass;
extern G__linked_taginfo G__G__GuiHtmlLN_TBuffer;
extern G__linked_taginfo G__G__GuiHtmlLN_TMemberInspector;
extern G__linked_taginfo G__G__GuiHtmlLN_TObject;
extern G__linked_taginfo G__G__GuiHtmlLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__GuiHtmlLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__GuiHtmlLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GuiHtmlLN_TTimer;
extern G__linked_taginfo G__G__GuiHtmlLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__GuiHtmlLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__GuiHtmlLN_Event_t;
extern G__linked_taginfo G__G__GuiHtmlLN_ColorStruct_t;
extern G__linked_taginfo G__G__GuiHtmlLN_TGObject;
extern G__linked_taginfo G__G__GuiHtmlLN_TQObject;
extern G__linked_taginfo G__G__GuiHtmlLN_TGWindow;
extern G__linked_taginfo G__G__GuiHtmlLN_TGFont;
extern G__linked_taginfo G__G__GuiHtmlLN_TGIdleHandler;
extern G__linked_taginfo G__G__GuiHtmlLN_TGInsets;
extern G__linked_taginfo G__G__GuiHtmlLN_THashTable;
extern G__linked_taginfo G__G__GuiHtmlLN_TGFrame;
extern G__linked_taginfo G__G__GuiHtmlLN_TGCompositeFrame;
extern G__linked_taginfo G__G__GuiHtmlLN_TGString;
extern G__linked_taginfo G__G__GuiHtmlLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__GuiHtmlLN_TGVerticalFrame;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHorizontalFrame;
extern G__linked_taginfo G__G__GuiHtmlLN_TGMainFrame;
extern G__linked_taginfo G__G__GuiHtmlLN_TGMenuBar;
extern G__linked_taginfo G__G__GuiHtmlLN_TGPopupMenu;
extern G__linked_taginfo G__G__GuiHtmlLN_TGStatusBar;
extern G__linked_taginfo G__G__GuiHtmlLN_TGComboBox;
extern G__linked_taginfo G__G__GuiHtmlLN_TGTextBuffer;
extern G__linked_taginfo G__G__GuiHtmlLN_TGTextEntry;
extern G__linked_taginfo G__G__GuiHtmlLN_TGPictureButton;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtml;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlBrowser;
extern G__linked_taginfo G__G__GuiHtmlLN_TGWidget;
extern G__linked_taginfo G__G__GuiHtmlLN_TGView;
extern G__linked_taginfo G__G__GuiHtmlLN_TImage;
extern G__linked_taginfo G__G__GuiHtmlLN_SHtmlStyle_t;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlElement;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlMarkupElement;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlTable;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlListStart;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlMapArea;
extern G__linked_taginfo G__G__GuiHtmlLN_SHtmlExtensions_t;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlImageMarkup;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlImage;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlForm;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlInput;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlAnchor;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlScript;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlBlock;
extern G__linked_taginfo G__G__GuiHtmlLN_SHtmlStyleStack_t;
extern G__linked_taginfo G__G__GuiHtmlLN_TGHtmlLayoutContext;
extern G__linked_taginfo G__G__GuiHtmlLN_GcCache_t;
extern G__linked_taginfo G__G__GuiHtmlLN_SHtmlIndex_t;
extern G__linked_taginfo G__G__GuiHtmlLN_SHtmlTokenMap_t;
extern G__linked_taginfo G__G__GuiHtmlLN_TGListBox;

/* STUB derived class for protected member access */
