url http://www.in.gr/entertainment/
include_re {/article/\?aid=[0-9]{4,}$}
htmltidy_feed_p 0
htmltidy_article_p 0
xpath_article_title {returnstring(//div[@class="text"]//h1)}
xpath_article_body {returntext(//div[@class="articleText"])}
xpath_article_image {
    {values(//div[@class="photo"]//div[@data-img]/@data-img)}
}
xpath_article_date {returndate(string(//div[@class="date"]),"%A %d %B, H:%M","el_GR")}
xpath_article_modified_time {}

